version: '3'

services:
    app1:
        build: app/
        command: python main.py
        environment:
            APP_ID: '1'
    app2:
        build: app/
        command: python main.py
        environment:
            APP_ID: '2'
    app3:
        build: app/
        command: python main.py
        environment:
            APP_ID: '3'
    lb:
        build: lb/
        ports:
            - "8080:8080"

